ALTER TABLE IF EXISTS user_data
    ADD COLUMN IF NOT EXISTS verificationCode VARCHAR(1024) NOT NULL DEFAULT 'preRegistered',
    ADD COLUMN IF NOT EXISTS status SMALLINT NOT NULL DEFAULT 1;

ALTER TABLE IF EXISTS cook
    ADD COLUMN IF NOT EXISTS verificationCode VARCHAR(1024) NOT NULL DEFAULT 'preRegistered',
    ADD COLUMN IF NOT EXISTS status SMALLINT NOT NULL DEFAULT 1;