spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: secret123

  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true